name: 'Gitlab Sync'
description: 'Action to synchronize code to GitLab.'

branding:
  icon: upload-cloud
  color: gray-dark

inputs:
  url:
    description: 'Gitlab repo URL'
    required: true
  username:
    description: 'Gitlab username'
    required: true
  token:
    description: 'Gitlab token'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        INPUT_TARGET_URL: ${{ inputs.url }}
        INPUT_TARGET_USERNAME: ${{ inputs.username }}
        INPUT_TARGET_TOKEN: ${{ inputs.token }}
        GITHUB_EVENT_REF: ${{ github.event.ref }}
