name: Build

on: 
  push:
    branches:
      - master
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'

jobs:
  shellcheck:
    name: Check
    uses: ./.github/workflows/check.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: shellcheck
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      - name: Publish new version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com 
          git tag -fa v${{ vars.MINOR }} -m "Update v${{ vars.MINOR }} tag"
          git push origin v${{ vars.MINOR }} --force
      -
        name: Increment minor version
        run: echo "NEW_MINOR=$((${{ vars.MINOR }}+1))" >> $GITHUB_ENV
      -
        name: Update minor version variable
        uses: kroese/set-variable@v4
        with:
          name: 'MINOR'
          value: ${{ env.NEW_MINOR }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
