name: Build

on: 
  workflow_dispatch:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - '.dockerignore'
      - '.github/**'
      - '.github/workflows/**'
      - 'action.yml'

jobs:
  shellcheck:
    name: Check
    uses: ./.github/workflows/check.yml

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: shellcheck
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
      -
        name: Create Release
        uses: action-pack/github-release@v6
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag: "v${{ vars.MAJOR }}.${{ vars.MINOR }}"
          title: "v${{ vars.MAJOR }}.${{ vars.MINOR }}"
          body: "Release v${{ vars.MAJOR }}.${{ vars.MINOR }}"
      -
        name: Update major release
        uses: action-pack/github-release@v6
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          tag: "v${{ vars.MAJOR }}"
          title: "v${{ vars.MAJOR }}"
          body: "Release v${{ vars.MAJOR }}"
      -
        name: Increment minor version
        uses: action-pack/increment@v2
        with:
          name: 'MINOR'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
